language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rootdocker1/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true rootdocker1/react-test npm test

after_success:
  - docker build -t rootdocker1/multi-client ./client
  - docker build -t rootdocker1/multi-nginx ./nginx
  - docker build -t rootdocker1/multi-server ./server
  - docker build -t rootdocker1/multi-worker ./worker
  - echo $DOCKER_PASSWORD
  - echo $DOCKER_ID
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rootdocker1/multi-client
  - docker push rootdocker1/multi-nginx
  - docker push rootdocker1/multi-server
  - docker push rootdocker1/multi-worker

  deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-369826655746
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY